# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Italo Freitas
email: itallo.freitass@gmail.com
sobremim: "Profissional de TI e entusiasta da área de Segurança da Informação. Técnico de Redes de Computadores e estudante de graduação em Sistemas de Informação pela UniFanor | Wydem. " 
baseurl: "" # https://italofreitas.github.io || the subpath of your site, e.g. /blog
url: "https://italofreitas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyll-twitter
github_username:  jekyll-github

# Build settings
markdown: kramdown
permalink: /blog/:year/:title # Refazer essa alteração e a de cima quando for subir pro GITHUB.
theme: minima
plugins:
  - jekyll-feed


#Social Profile
linkedin: https://www.linkedin.com/in/italofreitas
github:	https://github.com/ItaloFreitas
instagram: https://www.instagram.com/itallofreitas/
twitter: https://twitter.com.br
facebook: https://facebook.com.br

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
